pipelines:
  test:
    blubberfile: blubber.yaml
    stages:
      - name: run-test
        build: test
        run: false
  publish:
    blubberfile: blubber.yaml
    stages:
      - name: staticbz
        build: staticbz
        publish:
          image:
            tags: [staticbz]
      - name: fifteenwp
        build: fifteenwp
        publish:
          image:
            tags: [fifteenwp]
